version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mynetwork

  nodejs:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always 
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./app:/app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
